# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: 百度
    url: https://baidu.com
  - name: xhemj
    url: https://xhemj.js.org
  - name: ERSS名言
    url: https://mingyan.js.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://xhemj.js.org/logo.png
  name: Xhemj Status
  introTitle: "Xhemj Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
