owner: xhemj
repo: upptime
user-agent: xhemj-bot
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
commitMessages:
  commitAuthorName: "Xhemj Bot"
  commitAuthorEmail: "xhemj_service@126.com"
sites:
  - name: ERSS Mingyan (Vercel)
    url: https://mingyan.js.org
  - name: ERSS Mingyan (Github + Cloudflare)
    url: https://i.xhemj.eu.org
  - name: ERSS Mingyan (Coding)
    url: https://cn.mingyan.js.org
  - name: xhemj (Vercel)
    url: https://xhemj.js.org
  - name: xhemj (Gitee)
    url: https://xhemj.gitee.io
assignees:
  - xhemj-bot
  - xhemj
status-website:
  cname: status.xhemj.eu.org
  logoUrl: https://xhemj.js.org/logo.png
  favicon: https://xhemj.js.org/logo.png
  name: Xhemj Status
  introTitle: "Xhemj Status"
  introMessage: 
  # apiBaseUrl: https://ghapi.xhemj.eu.org
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  allSystemsOperational: 所有站点都正常运行
  incidentReport: "#$NUMBER 号事件报告 →"
  incidentTitle: $NUMBER 号事件明细
  incidentDetails: 事件明细
  incidentFixed: 修复
  incidentOngoing: 进行中
  incidentOpenedAt: 打开于
  incidentClosedAt: 关闭于
  incidentSubscribe: 订阅更新
  incidentViewOnGitHub: 在GitHub上查看
  incidentCommentSummary: 由 $AUTHOR 在 $DATE 发表
  incidentBack: ← 返回所有事件
  pastIncidents: 历史事件
  pastIncidentsResolved: 在 $MINUTES 分钟内的 $POSTS 条回复中得到解决
  liveStatus: 实时状态
  overallUptime: "正常运行时间：$UPTIME"
  overallUptimeTitle: 正常运行时间
  averageResponseTime: "平均响应时间：$TIMEms"
  averageResponseTimeTitle: 平均响应
  sevelDayResponseTime: 7天响应记录
  responseTimeMs: 响应时间 (ms)
  up: 正常
  down: 故障
  ms: ms
  loading: 加载中
  navGitHub: GitHub
  footer: powered by [Upptime](https://upptime.js.org)
