owner: xhemj
repo: upptime
user-agent: xhemj-bot
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
commitMessages:
  commitAuthorName: "Xhemj Bot"
  commitAuthorEmail: "xhemj_service@126.com"
sites:
  - name: ERSS Mingyan (Vercel)
    url: https://mingyan.js.org
  - name: ERSS Mingyan (Github + Cloudflare)
    url: https://i.xhemj.eu.org
  - name: ERSS Mingyan (Coding)
    url: https://cn.mingyan.js.org
  - name: xhemj (Vercel)
    url: https://xhemj.js.org
  - name: xhemj (Gitee)
    url: https://xhemj.gitee.io
assignees:
  - xhemj-bot
  - xhemj
status-website:
  cname: status.xhemj.eu.org
  logoUrl: https://xhemj.js.org/logo.png
  favicon: https://xhemj.js.org/logo.png
  name: Xhemj Status
  introTitle: "Xhemj Status"
  introMessage: 
  apiBaseUrl: https://ghapi.xhemj.eu.org
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
