# Change these first
owner: xhemj # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: ERSS Mingyan (Vercel)
    url: https://mingyan.js.org
  - name: ERSS Mingyan (Github + Cloudflare)
    url: https://i.xhemj.eu.org
  - name: ERSS Mingyan (Coding)
    url: https://cn.mingyan.js.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.xhemj.eu.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://xhemj.js.org/logo.png
  name: Xhemj Status
  introTitle: "Xhemj Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
skipDescriptionUpdate: true
skipTopicsUpdate: true

commitMessages:
  commitAuthorName: "Xhemj Bot"
  commitAuthorEmail: "xhemj_service@126.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
