# Change these first
owner: xhemj # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Baidu
    url: https://www.baidu.com
  - name: xhemj
    url: https://xhemj.js.org
  - name: ERSS Mingyan
    url: https://mingyan.js.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.xhemj.eu.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://xhemj.js.org/logo.png
  name: Xhemj Status
  introTitle: "Xhemj Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

skipDescriptionUpdate: true
skipTopicsUpdate: true
commitMessages:
  commitAuthorName: "Xhemj Bot"
  commitAuthorEmail: "ersskrz@163.com"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
